#if !canImport(ObjectiveC)
import XCTest

extension ThreadSafeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ThreadSafeTests = [
        ("testConcurrentAccess", testConcurrentAccess),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ThreadSafeTests.__allTests__ThreadSafeTests),
    ]
}
#endif
